language: node_js
node_js:
  - '10'
  - '9'
  - '8'
cache:
  directories:
    - ~/.npm
script: npm run build && npm run qa
# Demo deployment
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
