language: node_js
node_js:
  - '10'
  - '9'
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn build
  - yarn qa
after_success:
  - travis-deploy-once && codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
